### ISSUE TITLE
展示的预测图是否是切割预测之后拼接的？

### ISSUE THREAD

**Issue by Gmgge** [yearing1017/CCNet_PyTorch#3]

**Comment by Gmgge** [comment]
可以看到的是，你展示的预测大图中存在的预测切割痕迹，不知道你是否使用了重叠切割这一方法？

**Comment by yearing1017** [comment]
@Gmgge  训练是切割的小图训练，预测时也是小图预测完成进行拼接，因为显存不够的原因

**Comment by Gmgge** [comment]
是否因为你的切割重叠像素太少，以至于拼接的时候产生撕裂的情况？
我之前也发现了这种错误，我调整了切割的代码以及拼接的代码基本不会在出现这一错误，可以提升一点精度，如果您有需要的话，很高兴和你沟通交流，我也在做遥感图像以及无人机影像分割这一方向。
