### ISSUE TITLE
为什么cc模块和deeplab的aspp模块并行 精度变化那么大，是不是说明cc模块是有问题的，并没有文章那么有效

### ISSUE THREAD

**Issue by swjtulinxi** [yearing1017/CCNet_PyTorch#4]

**Comment by yearing1017** [comment]
毕竟deeplab是真的sota，你懂得 @swjtulinxi

**Comment by swjtulinxi** [comment]
那也不至于差那么多吧，，那说明cc对结果是有害的，不如单独用aspp

**Comment by yearing1017** [comment]
> 那也不至于差那么多吧，，那说明cc对结果是有害的，不如单独用aspp

也不能这样说，因为我做的实验是基于我自己的数据，适用性也是一个重要的原因，而且已经证明了加上是有益的

**Comment by swjtulinxi** [comment]
博主你好，请问你觉得比如说像你做的这些工作，写硕士毕业论文工作量够吗，我是做遥感图像分割的硕士，，因为我实在不晓得还能有什么做的，不也就是拿别人的模型跑一跑吗，，，求指点一下

**Comment by yearing1017** [comment]
> 博主你好，请问你觉得比如说像你做的这些工作，写硕士毕业论文工作量够吗，我是做遥感图像分割的硕士，，因为我实在不晓得还能有什么做的，不也就是拿别人的模型跑一跑吗，，，求指点一下

肯定不够啊，这只是平常自己做的实验，就想放上去而已，再努力呗，共勉！
